image: maven:latest

build:
  script:
  - chmod +x build.sh
  - ./build.sh
  - cp target/IRCBouncer.jar .
  - ls -la *
  artifacts:
    name: "IRCBouncer_${CI_BUILD_REF_NAME}"
    paths:
    - IRCBouncer.jar
    - config.ini
    - accounts.ini