language: java
jdk: oraclejdk8

script:
    - chmod +x build.sh
    - ./build.sh
    - mkdir Release/
    - mkdir Release/saves/
    - cp target/IRCBouncer.jar Release/
    - cp ./*.ini Release/
    - zip -r release.zip Release/
    - ls -la *
    
notifications:
    email: false

deploy:
    provider: releases
    api_key: ${api_key}
    file: "release.zip"
    skip_cleanup: true
    on:
        all_branches: true
        tags: true